import __wbg_init from "./gen/background.js";
import { listen } from "./gen/background.js";

// run the wasm initializer before calling wasm methods
// the initializer is generated by wasm_pack
(async () => {
  await __wbg_init();
})();

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  listen(request).then((resp) => sendResponse(resp));
  return true; // return true to indicate you want to send a response asynchronously
});

chrome.action.onClicked.addListener(async () => {
  chrome.tabs.create({
    url: "index.html",
    selected: true,
  });
});
