[tasks.build]
dependencies = ["wasm_build", "copy"]

[tasks.wasm_build]
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "--help" }
command = "wasm-pack"
args = [
    "build",
    "--release",
    "--no-typescript",
    "--out-dir",
    "../extension/background",
    "--out-name",
    "background",
    "--target",
    "web",
]

[tasks.copy]
script_runner = "@shell"
script = '''
cp index.js ../extension/background/
'''
