[tasks.install]
script_runner = "@shell"
script = '''
pnpm install
'''

[tasks.fmt]
install_crate = { crate_name = "leptosfmt", binary = "leptosfmt", test_arg = "--help" }
command = "cargo"
args = ["fmt"]

[tasks.build]
install_crate = { crate_name = "trunk", binary = "trunk", test_arg = "--help" }
command = "trunk"
args = ["build", "--release", "--dist", "../extension/popup"]
dependencies = ["install"]
